//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediensen &amp; dess mängd har lagts till!.
        /// </summary>
        internal static string Action_Amount_Added {
            get {
                return ResourceManager.GetString("Action_Amount_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mängden &amp; ingrediensen har tagits bort!.
        /// </summary>
        internal static string Action_Amount_Deleted {
            get {
                return ResourceManager.GetString("Action_Amount_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediensen &amp; dess mängd har uppdaterats!.
        /// </summary>
        internal static string Action_Amount_Updated {
            get {
                return ResourceManager.GetString("Action_Amount_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptet har lagts till!.
        /// </summary>
        internal static string Action_Recipe_Added {
            get {
                return ResourceManager.GetString("Action_Recipe_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptet har tagits bort!.
        /// </summary>
        internal static string Action_Recipe_Deleted {
            get {
                return ResourceManager.GetString("Action_Recipe_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptet har uppdaterats!.
        /// </summary>
        internal static string Action_Recipe_Updated {
            get {
                return ResourceManager.GetString("Action_Recipe_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade då mängden &amp; ingrediensen skulle tas bort..
        /// </summary>
        internal static string Amount_Deleting_Error {
            get {
                return ResourceManager.GetString("Amount_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade då mängden &amp; ingrediensen skulle läggas till..
        /// </summary>
        internal static string Amount_Insert_Error {
            get {
                return ResourceManager.GetString("Amount_Insert_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mängden &amp; ingrediensen med nummer {0} hittades inte..
        /// </summary>
        internal static string Amount_Not_Found {
            get {
                return ResourceManager.GetString("Amount_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade då mängden &amp; ingrediensen skulle hämtas..
        /// </summary>
        internal static string Amount_Selecting_Error {
            get {
                return ResourceManager.GetString("Amount_Selecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade då mängden &amp; ingrediensen skulle uppdateras..
        /// </summary>
        internal static string Amount_Updating_Error {
            get {
                return ResourceManager.GetString("Amount_Updating_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när datan skulle hämtas....
        /// </summary>
        internal static string Generic_DAL_Error_Message {
            get {
                return ResourceManager.GetString("Generic_DAL_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade då receptet skulle tas bort..
        /// </summary>
        internal static string Recipe_Deleting_Error {
            get {
                return ResourceManager.GetString("Recipe_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade då receptet skulle läggas till..
        /// </summary>
        internal static string Recipe_Insert_Error {
            get {
                return ResourceManager.GetString("Recipe_Insert_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptet med nummer {0} hittades inte..
        /// </summary>
        internal static string Recipe_Not_Found {
            get {
                return ResourceManager.GetString("Recipe_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade då receptet skulle hämtas..
        /// </summary>
        internal static string Recipe_Selecting_Error {
            get {
                return ResourceManager.GetString("Recipe_Selecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade då receptet skulle uppdateras..
        /// </summary>
        internal static string Recipe_Updating_Error {
            get {
                return ResourceManager.GetString("Recipe_Updating_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektet klarade inte valderingen..
        /// </summary>
        internal static string Validation_Object_Error {
            get {
                return ResourceManager.GetString("Validation_Object_Error", resourceCulture);
            }
        }
    }
}
